[features]
seeds = false
skip-lint = false
[programs.devnet]
gifportalsol = "7zCUzvH7h5XmKbsq2Qu9a7QMDgJV3gnMJ1afTvakCWrw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/xubuntu/.config/solana/id.json"

[scripts]
test = "node tests/gifportalsol.js"
